# Travis Badge Markdown (add to README.md): [![Build Status](https://secure.travis-ci.org/kylenoble/meteor-Meteor-Node-Summary.png?branch=master)](https://travis-ci.org/kylenoble/meteor-Meteor-Node-Summary)
sudo: required
language: node_js
node_js:
  - "0.12"

before_install:
  - "curl -L http://git.io/ejPSng | /bin/sh"
